#!/usr/bin/env python3
"""Run small end-to-end demos for Praxis modules."""

from __future__ import annotations

import argparse
from pathlib import Path

from praxis.cli import main as praxis_main
from praxis.paths import default_root


MODULES = {
    "core": "Capture one local source, index it, and search it with explanations.",
    "reach": "Create one fixture GTM client, produce evidence, and build a context pack.",
    "agency": "Create two fixture clients and run one workflow across both.",
    "all": "Run the Core, Reach, and Agency demos.",
}

CORE_SOURCE = """# Praxis Core Demo Source

Praxis Core turns source material into searchable, source-traceable agent knowledge.

The important idea is not just retrieval. Praxis keeps raw evidence, summaries,
chunks, source IDs, hashes, graph links, confidence metadata, conflict warnings,
and rollback records attached to the knowledge agents use.

This demo source exists so a new user can see the Core loop without needing a
web page, API key, or private corpus.

## What An Agent Can Reuse

- Capture useful sources during real work.
- Search them later with semantic, keyword, and graph signals.
- Inspect why a result matched before trusting it.
- Promote selected knowledge into reusable instructions or references.
"""


def run_step(root: Path, label: str, args: list[str]) -> int:
    print(f"\n== {label} ==")
    print("praxis " + " ".join(args))
    code = praxis_main(["--root", str(root), *args])
    if code:
        print(f"stopped: {label} returned {code}")
    return int(code)


def write_core_demo_source(root: Path) -> Path:
    path = root / "research" / "demo_sources" / "praxis-core-demo.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CORE_SOURCE, encoding="utf-8")
    return path


def demo_core(root: Path) -> int:
    print("# Praxis Core demo")
    print("\nThis demo captures one local source, writes provisional SkillGraph memory, chunks it, embeds it, and searches it.")
    source_path = write_core_demo_source(root)
    steps = [
        ("Initialize relational DB", ["init-db"]),
        ("Initialize SkillGraph", ["init-graph"]),
        (
            "Ingest demo source",
            [
                "ingest",
                str(source_path),
                "--title",
                "Praxis Core Demo Source",
                "--source-type",
                "docs",
                "--source-id",
                "src:praxis-core-demo",
                "--freshness-window-days",
                "90",
                "--notes",
                "Generated by praxis demo core.",
            ],
        ),
        ("Chunk changed sources", ["chunk", "--changed-only", "--no-runtimes", "--no-skills"]),
        ("Embed chunks locally", ["embed", "--provider", "local-hash"]),
        (
            "Search with explanations",
            ["search", "how does Praxis keep agent knowledge reusable and traceable?", "--explain", "--limit", "3"],
        ),
    ]
    for label, args in steps:
        code = run_step(root, label, args)
        if code:
            return code
    print(
        """
Core demo complete.

You saw the full source-to-search path:
  source -> evidence archive -> provisional SkillGraph memory -> chunks -> embeddings -> explained search.

Try next:
  praxis changes list
  praxis conflicts list
  praxis export-skill-refs
""".strip()
    )
    return 0


def demo_reach(root: Path, client_id: str, profile: str) -> int:
    print("# Praxis Reach demo")
    print("\nThis demo uses fixture GTM data, so it does not need live credentials.")
    steps = [
        ("Initialize Reach", ["reach", "init"]),
        ("Create fixture client", ["agency", "fixture", "create", client_id, "--profile", profile, "--overwrite"]),
        ("Run weekly GTM review", ["agency", "run", "weekly_gtm_review", "--clients", client_id, "--context"]),
        ("List evidence", ["reach", "evidence", "list", "--client", client_id]),
        ("Check freshness", ["reach", "stale", "list", "--client", client_id, "--all"]),
    ]
    for label, args in steps:
        code = run_step(root, label, args)
        if code:
            return code
    print(
        f"""
Reach demo complete.

You saw the zero-copy evidence path:
  fixture systems -> query manifest -> evidence card -> context pack.

Try next:
  praxis reach evidence show "ev:..."
  praxis reach context build weekly_gtm_review --client {client_id}
""".strip()
    )
    return 0


def demo_agency(root: Path) -> int:
    print("# Praxis Reach for Agencies demo")
    print("\nThis demo creates two fixture clients and runs one GTM workflow across both.")
    steps = [
        ("Initialize Reach", ["reach", "init"]),
        ("Create Acme fixture client", ["agency", "fixture", "create", "acme", "--profile", "b2b-saas", "--overwrite"]),
        ("Create Beta fixture client", ["agency", "fixture", "create", "beta", "--profile", "local-services", "--overwrite"]),
        ("List clients", ["agency", "client", "list", "--include-archived"]),
        ("Run weekly GTM review across clients", ["agency", "run", "weekly_gtm_review", "--clients", "acme,beta", "--context"]),
        ("Show stale context report", ["agency", "stale-context-report", "--all"]),
    ]
    for label, args in steps:
        code = run_step(root, label, args)
        if code:
            return code
    print(
        """
Agency demo complete.

You saw the multi-client path:
  client capsules -> per-client fixture data -> shared workflow -> per-client evidence/context.

Try next:
  praxis agency client show acme
  praxis agency client show beta
  praxis agency client export acme
""".strip()
    )
    return 0


def list_demos() -> int:
    print("# Praxis demos\n")
    for module, description in MODULES.items():
        print(f"- {module}: {description}")
    print("\nRun one with:")
    print("  praxis demo core")
    print("  praxis demo reach")
    print("  praxis demo agency")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="praxis demo", description=__doc__)
    parser.add_argument("module", nargs="?", choices=sorted(MODULES), help="Demo module to run.")
    parser.add_argument("--root", default=str(default_root()), help="Praxis checkout/workspace root.")
    parser.add_argument("--client", default="demo", help="Client id for the Reach demo.")
    parser.add_argument("--profile", default="b2b-saas", choices=["b2b-saas", "local-services"], help="Fixture profile for the Reach demo.")
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    if not args.module:
        return list_demos()

    root = Path(args.root).expanduser().resolve()
    if args.module == "core":
        return demo_core(root)
    if args.module == "reach":
        return demo_reach(root, client_id=args.client, profile=args.profile)
    if args.module == "agency":
        return demo_agency(root)
    for runner in (
        demo_core,
        lambda value: demo_reach(value, client_id=args.client, profile=args.profile),
        demo_agency,
    ):
        code = runner(root)
        if code:
            return code
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
